/**
 * Static cache keys for the bootstrap endpoint.
 * Only keys with NO request-varying suffixes are included.
 */
export const BOOTSTRAP_CACHE_KEYS: Record<string, string> = {
  earthquakes:      'seismology:earthquakes:v1',
  outages:          'infra:outages:v1',
  serviceStatuses:  'infra:service-statuses:v1',
  sectors:          'market:sectors:v1',
  etfFlows:         'market:etf-flows:v1',
  macroSignals:     'economic:macro-signals:v1',
  bisPolicy:        'economic:bis:policy:v1',
  bisExchange:      'economic:bis:eer:v1',
  bisCredit:        'economic:bis:credit:v1',
  shippingRates:    'supply_chain:shipping:v2',
  chokepoints:      'supply_chain:chokepoints:v4',
  chokepointTransits: 'supply_chain:chokepoint_transits:v1',
  minerals:         'supply_chain:minerals:v2',
  giving:           'giving:summary:v1',
  climateAnomalies: 'climate:anomalies:v1',
  wildfires:        'wildfire:fires:v1',
  marketQuotes:     'market:stocks-bootstrap:v1',
  commodityQuotes:  'market:commodities-bootstrap:v1',
  cyberThreats:     'cyber:threats-bootstrap:v2',
  techReadiness:    'economic:worldbank-techreadiness:v1',
  progressData:     'economic:worldbank-progress:v1',
  renewableEnergy:  'economic:worldbank-renewable:v1',
  positiveGeoEvents: 'positive_events:geo-bootstrap:v1',
  theaterPosture:   'theater_posture:sebuf:stale:v1',
  riskScores:       'risk:scores:sebuf:stale:v1',
  naturalEvents:    'natural:events:v1',
  flightDelays:     'aviation:delays-bootstrap:v1',
  insights:         'news:insights:v1',
  predictions:      'prediction:markets-bootstrap:v1',
  cryptoQuotes:     'market:crypto:v1',
  gulfQuotes:       'market:gulf-quotes:v1',
  stablecoinMarkets: 'market:stablecoins:v1',
  unrestEvents:     'unrest:events:v1',
  iranEvents:       'conflict:iran-events:v1',
  ucdpEvents:       'conflict:ucdp-events:v1',
  temporalAnomalies: 'temporal:anomalies:v1',
  weatherAlerts:    'weather:alerts:v1',
  spending:         'economic:spending:v1',
  techEvents:       'research:tech-events-bootstrap:v1',
  gdeltIntel:       'intelligence:gdelt-intel:v1',
  correlationCards: 'correlation:cards-bootstrap:v1',
  securityAdvisories: 'intelligence:advisories-bootstrap:v1',
  forecasts:          'forecast:predictions:v2',
  customsRevenue:     'trade:customs-revenue:v1',
};

export const BOOTSTRAP_TIERS: Record<string, 'slow' | 'fast'> = {
  bisPolicy: 'slow', bisExchange: 'slow', bisCredit: 'slow',
  minerals: 'slow', giving: 'slow', sectors: 'slow',
  progressData: 'slow', renewableEnergy: 'slow',
  etfFlows: 'slow', shippingRates: 'fast', wildfires: 'slow',
  climateAnomalies: 'slow', cyberThreats: 'slow', techReadiness: 'slow',
  theaterPosture: 'fast', naturalEvents: 'slow',
  cryptoQuotes: 'slow', gulfQuotes: 'slow', stablecoinMarkets: 'slow',
  unrestEvents: 'slow', ucdpEvents: 'slow', techEvents: 'slow',
  earthquakes: 'fast', outages: 'fast', serviceStatuses: 'fast',
  macroSignals: 'fast', chokepoints: 'fast', chokepointTransits: 'fast', riskScores: 'fast',
  marketQuotes: 'fast', commodityQuotes: 'fast', positiveGeoEvents: 'fast',
  flightDelays: 'fast', insights: 'fast', predictions: 'fast',
  iranEvents: 'fast', temporalAnomalies: 'fast', weatherAlerts: 'fast',
  spending: 'fast', gdeltIntel: 'fast', correlationCards: 'fast',
  securityAdvisories: 'slow',
  forecasts: 'fast',
  customsRevenue: 'slow',
};
